version: '3'

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: "mysql/mysql-server:8.0"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
            MYSQL_USER: symfony
            MYSQL_PASSWORD: 12345

        volumes:
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            - ./db-data:/var/lib/mysql:rw
        ports:
            - "32769:3306"
###< doctrine/doctrine-bundle ###
